import "dotenv/config";

const ENV = process.env;

const config = {
  RESPONSE_CONTENT_TYPE: ENV.RESPONSE_CONTENT_TYPE || "application/json",
  HTML_CONTENT_TYPE: "text/html; charset=utf-8",
  DEFAULT_PORT: Number(ENV.PORT || 3100),
  HTTP_HOST: ENV.HTTP_HOST || "0.0.0.0",
  SERVICE_NAME: ENV.SERVICE_NAME || "@sha3/polymarket-model-farm",
  COLLECTOR_BASE_URL: ENV.COLLECTOR_BASE_URL || "http://localhost:3000",
  MODEL_STORAGE_DIR: ENV.MODEL_STORAGE_DIR || "./var/model",
  HISTORY_STORAGE_DIR: ENV.HISTORY_STORAGE_DIR || "./var/history",
  MODEL_GRU_UNITS_5M: Number(ENV.MODEL_GRU_UNITS_5M || 48),
  MODEL_GRU_UNITS_15M: Number(ENV.MODEL_GRU_UNITS_15M || 72),
  MODEL_DROPOUT_RATE: Number(ENV.MODEL_DROPOUT_RATE || 0.15),
  MODEL_LEARNING_RATE: Number(ENV.MODEL_LEARNING_RATE || 0.0005),
  MODEL_L2_REGULARIZATION: Number(ENV.MODEL_L2_REGULARIZATION || 0.00001),
  TRAINING_EPOCHS_PER_MARKET: Number(ENV.TRAINING_EPOCHS_PER_MARKET || 2),
  TRAINING_BATCH_SIZE: Number(ENV.TRAINING_BATCH_SIZE || 1),
  TRAINING_MAX_MARKETS_PER_CYCLE: Number(ENV.TRAINING_MAX_MARKETS_PER_CYCLE || 1),
  TRAINING_POLL_INTERVAL_MS: Number(ENV.TRAINING_POLL_INTERVAL_MS || 5000),
  TRAINING_IDLE_BACKOFF_MS: Number(ENV.TRAINING_IDLE_BACKOFF_MS || 60000),
  TRAINING_CLOSE_GRACE_MS: Number(ENV.TRAINING_CLOSE_GRACE_MS || 20000),
  DELTA_TARGET_SCALE: Number(ENV.DELTA_TARGET_SCALE || 0.02),
  RECENT_TARGET_DELTA_LIMIT: Number(ENV.RECENT_TARGET_DELTA_LIMIT || 32),
  MIN_TRAINED_MARKETS_FOR_PREDICTION: Number(ENV.MIN_TRAINED_MARKETS_FOR_PREDICTION || 100),
  PREDICTION_HISTORY_LIMIT: Number(ENV.PREDICTION_HISTORY_LIMIT || 250),
  CONFIDENCE_DELTA_FACTOR: Number(ENV.CONFIDENCE_DELTA_FACTOR || 0.75),
  LIVE_PREDICTION_PROGRESS: Number(ENV.LIVE_PREDICTION_PROGRESS || 0.75),
  LIVE_PREDICTION_POLL_INTERVAL_MS: Number(ENV.LIVE_PREDICTION_POLL_INTERVAL_MS || 15000),
  COLLECTOR_STATE_CACHE_TTL_MS: Number(ENV.COLLECTOR_STATE_CACHE_TTL_MS || 5000),
  COLLECTOR_MARKET_CACHE_TTL_MS: Number(ENV.COLLECTOR_MARKET_CACHE_TTL_MS || 15000),
  COLLECTOR_SNAPSHOT_CACHE_TTL_MS: Number(ENV.COLLECTOR_SNAPSHOT_CACHE_TTL_MS || 0),
} as const;

export default config;
