import "dotenv/config";

const ENV = process.env;

const config = {
  RESPONSE_CONTENT_TYPE: ENV.RESPONSE_CONTENT_TYPE || "application/json",
  HTTP_HOST: ENV.HTTP_HOST || "0.0.0.0",
  DEFAULT_PORT: Number(ENV.PORT || 4000),
  SERVICE_NAME: ENV.SERVICE_NAME || "@sha3/polymarket-model-farm",
  COLLECTOR_BASE_URL: ENV.COLLECTOR_BASE_URL || "http://localhost:3000",
  MODEL_STORAGE_DIR: ENV.MODEL_STORAGE_DIR || ".model-farm",
  TRAINING_POLL_INTERVAL_MS: Number(ENV.TRAINING_POLL_INTERVAL_MS || 5000),
  TRAINING_IDLE_BACKOFF_MS: Number(ENV.TRAINING_IDLE_BACKOFF_MS || 15000),
  TRAINING_EPOCHS_PER_MARKET: Number(ENV.TRAINING_EPOCHS_PER_MARKET || 1),
  TRAINING_BATCH_SIZE: Number(ENV.TRAINING_BATCH_SIZE || 1),
  TRAINING_CLOSE_GRACE_MS: Number(ENV.TRAINING_CLOSE_GRACE_MS || 5000),
  TRAINING_MAX_MARKETS_PER_CYCLE: Number(ENV.TRAINING_MAX_MARKETS_PER_CYCLE || 1),
  DELTA_TARGET_SCALE: Number(ENV.DELTA_TARGET_SCALE || 0.005),
  CONFIDENCE_SCALING_FACTOR: Number(ENV.CONFIDENCE_SCALING_FACTOR || 0.75),
  MODEL_GRU_UNITS_5M: Number(ENV.MODEL_GRU_UNITS_5M || 64),
  MODEL_GRU_UNITS_15M: Number(ENV.MODEL_GRU_UNITS_15M || 96),
  MODEL_DROPOUT_RATE: Number(ENV.MODEL_DROPOUT_RATE || 0.1),
  MODEL_LEARNING_RATE: Number(ENV.MODEL_LEARNING_RATE || 0.001),
  MODEL_L2_REGULARIZATION: Number(ENV.MODEL_L2_REGULARIZATION || 0.00001),
  MODEL_SEED: Number(ENV.MODEL_SEED || 42),
  PREDICTION_MAX_MARKETS_PER_REQUEST: Number(ENV.PREDICTION_MAX_MARKETS_PER_REQUEST || 32),
} as const;

export default config;
